"""retirements

Revision ID: 239bdb8b9bf6
Revises: 609c94a2ee5f
Create Date: 2026-06-05 04:51:16.754706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239bdb8b9bf6'
down_revision: Union[str, None] = '609c94a2ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retirements',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('current_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('monthly_contribution_minor', sa.BigInteger(), nullable=False),
    sa.Column('employer_match_bps', sa.Integer(), nullable=False),
    sa.Column('annual_return_bps', sa.Integer(), nullable=False),
    sa.Column('inflation_bps', sa.Integer(), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retirements')
    # ### end Alembic commands ###
