"""loan collateral

Revision ID: 609c94a2ee5f
Revises: dacfeed37679
Create Date: 2026-06-05 04:25:15.087160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609c94a2ee5f'
down_revision: Union[str, None] = 'dacfeed37679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secured', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('collateral_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_loans_collateral_plan_id_plans', 'plans', ['collateral_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_collateral_plan_id_plans', type_='foreignkey')
        batch_op.drop_column('collateral_plan_id')
        batch_op.drop_column('secured')

    # ### end Alembic commands ###
