"""holdings

Revision ID: acec7de9fbe6
Revises: 82264a4ffa8f
Create Date: 2026-06-04 20:33:18.149936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acec7de9fbe6'
down_revision: Union[str, None] = '82264a4ffa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=12), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('purity', sa.String(length=16), nullable=True),
    sa.Column('current_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('price_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_micro', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_column('quantity_micro')

    op.drop_table('holdings')
    # ### end Alembic commands ###
