"""loans table + ledger kind + nullable

Revision ID: daacf83e03ee
Revises: 1dffc81d30c6
Create Date: 2026-06-04 17:47:25.348500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daacf83e03ee'
down_revision: Union[str, None] = '1dffc81d30c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('interest_type', sa.String(length=10), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=12), nullable=False),
    sa.Column('repayment', sa.String(length=12), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=24), nullable=True))
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('funding_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('funding_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('kind')

    op.drop_table('loans')
    # ### end Alembic commands ###
