"""chits

Revision ID: dacfeed37679
Revises: 26b0e2444049
Create Date: 2026-06-04 23:01:05.918095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacfeed37679'
down_revision: Union[str, None] = '26b0e2444049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chits',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('chit_value_minor', sa.BigInteger(), nullable=False),
    sa.Column('n_members', sa.Integer(), nullable=False),
    sa.Column('commission_bps', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chits')
    # ### end Alembic commands ###
