"""plan memberships

Revision ID: fcb8126c1b40
Revises: daacf83e03ee
Create Date: 2026-06-04 18:35:24.727840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb8126c1b40'
down_revision: Union[str, None] = 'daacf83e03ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'user_id', name='uq_plan_member')
    )
    with op.batch_alter_table('plan_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_memberships_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_plan_memberships_plan_id'))

    op.drop_table('plan_memberships')
    # ### end Alembic commands ###
